objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Investment__c/fields/Available_to_Invest__c.field-meta.xml
<CustomField>
    <fullName>Available_to_Invest__c</fullName>
    <label>Available to Invest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

classes/InvestmentService.cls
public with sharing class InvestmentService {
    public static void updateAvailableToInvest(Map<Id,List<Decimal>> investmentAmountMap, String operation) {
        List<Investment__c> invs = [
            SELECT Id, Available_to_Invest__c
            FROM Investment__c
            WHERE Id IN : investmentAmountMap.keySet()
        ];

        for(Investment__c investment : invs){
            for(Decimal amount : investmentAmountMap.get(investment.Id)){
                if(operation == '+'){
                    investment.Available_to_Invest__c += amount;
                } else if(operation == '-'){
                    investment.Available_to_Invest__c -= amount;
                }
            }
        }

        update invs;
    }
}