objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount of money in this account</description>
    <inlineHelpText>Amount of money in this account</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Account__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

objects/Account__c/fields/Why__c.field-meta.xml
<CustomField>
    <fullName>Why__c</fullName>
    <description>Describe the purpose of this account, why it was opened.</description>
    <inlineHelpText>Describe the purpose of this account, why it was opened.</inlineHelpText>
    <label>Why?</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

objects/Goods__c/Goods__c.object-meta.xml
<CustomObject>
    <label>Goods</label>
    <nameField>
        <label>Goods Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Goods__c/fields/Current_Value__c.field-meta.xml
<CustomField>
    <fullName>Current_Value__c</fullName>
    <label>Current Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Goods__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Goods</relationshipLabel>
    <relationshipName>Goods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Goods__c/fields/No_Titles__c.field-meta.xml
<CustomField>
    <fullName>No_Titles__c</fullName>
    <label>No. Titles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Investment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Investments</relationshipLabel>
    <relationshipName>Investments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Investment__c/fields/Available_to_Invest__c.field-meta.xml
<CustomField>
    <fullName>Available_to_Invest__c</fullName>
    <label>Available to Invest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Vouchers</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

classes/InvestmentServiceTest.cls
@IsTest
public with sharing class InvestmentServiceTest {
    @IsTest
    static void insertGoods(){
        Account__c account = new Account__c(
            Amount__c = 5000.50,
            Type__c = 'Bank',
            Why__c = 'Testing account'
        );
        insert account;

        Investment__c inv = new Investment__c(
            Account__c = account.Id,
            Available_to_Invest__c = 1000.50,
            Name = 'Test Investment Record'
        );
        insert inv;

        List<Goods__c> goods = new List<Goods__c>();
        for(Integer i = 0; i < 2; i++){
            Goods__c g = new Goods__c();
            g.Name = 'Test Goods ' + i;
            g.Investment__c = inv.Id;
            g.No_Titles__c = 4;
            g.Unit_Cost__c = 100;
            g.Current_Value__c = 400;
            goods.add(g);
        }

        insert goods;

        Investment__c investmentRecord = [SELECT Id, Available_to_Invest__c FROM Investment__c WHERE Name = 'Test Investment Record' LIMIT 1];

        Assert.areEqual(200.50, investmentRecord.Available_to_Invest__c);
    }
}