objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount of money in this account</description>
    <inlineHelpText>Amount of money in this account</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

classes/UpdateAccountService.cls
public with sharing class UpdateAccountService {
    public static void updateAccountAmount(Map<Id, List<Decimal>> accountAmountMap, String operation){
        List<Account__c> accounts = [
            SELECT Id, Amount__c
            FROM Account__c
            WHERE Id IN : accountAmountMap.keySet()
        ];

        for(Account__c account : accounts){
            for(Decimal amount : accountAmountMap.get(account.Id)){
                if(operation == '+'){
                    account.Amount__c += amount;
                } else if(operation == '-'){
                    account.Amount__c -= amount;
                }
            }
        }

        update accounts;
    }
}