objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount of money in this account</description>
    <inlineHelpText>Amount of money in this account</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <description>Record every expense made</description>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Expense__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Expense__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Expensed Amount</description>
    <inlineHelpText>Expensed Amount</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Expense__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Expense Category.</description>
    <inlineHelpText>Expense Category.</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Clothes</fullName>
            </value>
            <value>
                <fullName>Amazon</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Family Support</fullName>
            </value>
            <value>
                <fullName>Public Transportation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Expense__c/fields/Why_Expense__c.field-meta.xml
<CustomField>
    <fullName>Why_Expense__c</fullName>
    <description>Describe why the expense.</description>
    <inlineHelpText>Describe why the expense.</inlineHelpText>
    <label>Why Expense?</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Goods__c/Goods__c.object-meta.xml
<CustomObject>
    <label>Goods</label>
    <nameField>
        <label>Goods Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Goods__c/fields/Current_Value__c.field-meta.xml
<CustomField>
    <fullName>Current_Value__c</fullName>
    <label>Current Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Goods__c/fields/Earned_Money__c.field-meta.xml
<CustomField>
    <fullName>Earned_Money__c</fullName>
    <formula>Current_Value__c -  Total_Invested__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Earned Money</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Goods__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Goods</relationshipLabel>
    <relationshipName>Goods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Goods__c/fields/No_Titles__c.field-meta.xml
<CustomField>
    <fullName>No_Titles__c</fullName>
    <label>No. Titles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Goods__c/fields/Total_Invested__c.field-meta.xml
<CustomField>
    <fullName>Total_Invested__c</fullName>
    <formula>No_Titles__c *  Unit_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Invested</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Investment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Investments</relationshipLabel>
    <relationshipName>Investments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Investment__c/fields/Available_to_Invest__c.field-meta.xml
<CustomField>
    <fullName>Available_to_Invest__c</fullName>
    <label>Available to Invest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Investment__c/fields/Invested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Invested_Amount__c</fullName>
    <label>Invested Amount</label>
    <summarizedField>Goods__c.Total_Invested__c</summarizedField>
    <summaryForeignKey>Goods__c.Investment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Investment__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <formula>Total_Earned__c / Invested_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

objects/Investment__c/fields/Total_Earned__c.field-meta.xml
<CustomField>
    <fullName>Total_Earned__c</fullName>
    <label>Total Earned</label>
    <summarizedField>Goods__c.Earned_Money__c</summarizedField>
    <summaryForeignKey>Goods__c.Investment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Investment__c/fields/Total_Invested_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Invested_Value__c</fullName>
    <formula>Invested_Amount__c +  Total_Earned__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Invested Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Revenue__c/Revenue__c.object-meta.xml
<CustomObject>
    <label>Revenue</label>
    <nameField>
        <label>Revenue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Revenue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Revenues</relationshipLabel>
    <relationshipName>Revenues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Revenue__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <inlineHelpText>Amount Revenue</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Revenue__c/fields/Revenue_Date__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Date__c</fullName>
    <label>Revenue Date</label>
    <type>Date</type>
</CustomField>

objects/Revenue__c/fields/Why_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Why_Revenue__c</fullName>
    <description>Describe details about revenue.</description>
    <inlineHelpText>Describe details about revenue.</inlineHelpText>
    <label>Why Revenue?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/AccountRelatedRecordsController.cls
public with sharing class AccountRelatedRecordsController {
    @AuraEnabled(cacheable=true)
    public static List<Investment__c> getInvestmentRelated(String accountId){
        return [
            SELECT Id, Name, Available_to_Invest__c, Account__c, Invested_Amount__c, Total_Invested_Value__c, Rate__c, Total_Earned__c
            FROM Investment__c
            WHERE Account__c =: accountId
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Expense__c> getExpensesRelated(String accountId){
        return [
            SELECT Id, Name, Amount__c, Account__c, Why_Expense__c, Category__c, Expense_Date__c
            FROM Expense__c
            WHERE Account__c =: accountId
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Revenue__c> getRevenuesRelated(String accountId){
        return [
            SELECT Id, Name, Amount__c, Account__c, Why_Revenue__c, Revenue_Date__c
            FROM Revenue__c
            WHERE Account__c =: accountId
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Goods__c> getGoodsRelated(String investmentId){
        return [
            SELECT Id, Name, Investment__c, Unit_Cost__c, No_Titles__c, Current_Value__c, Total_Invested__c, Earned_Money__c
            FROM Goods__c
            WHERE Investment__c =: investmentId
        ];
    }
}