objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount of money in this account</description>
    <inlineHelpText>Amount of money in this account</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Account__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

objects/Account__c/fields/Why__c.field-meta.xml
<CustomField>
    <fullName>Why__c</fullName>
    <description>Describe the purpose of this account, why it was opened.</description>
    <inlineHelpText>Describe the purpose of this account, why it was opened.</inlineHelpText>
    <label>Why?</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <description>Record every expense made</description>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Expense__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Expense__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Expensed Amount</description>
    <inlineHelpText>Expensed Amount</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Revenue__c/Revenue__c.object-meta.xml
<CustomObject>
    <label>Revenue</label>
    <nameField>
        <label>Revenue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Revenue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Revenues</relationshipLabel>
    <relationshipName>Revenues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Revenue__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <inlineHelpText>Amount Revenue</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Vouchers</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

classes/UpdateAccountServiceTest.cls
@IsTest
public with sharing class UpdateAccountServiceTest {
    @TestSetup
    static void makeData(){
        Account__c account = new Account__c(
            Amount__c = 5000.50,
            Type__c = 'Bank',
            Why__c = 'Testing account'
        );
        insert account;
    }

    @IsTest
    static void createExpenses(){
        Account__c account = [SELECT ID, Amount__c FROM Account__c LIMIT 1];

        List<Expense__c> newExps = new List<Expense__c>();
        for(Integer i = 0; i < 5; i++){
            Expense__c exp = new Expense__c();
            exp.Name = 'Test'+i;
            exp.Amount__c = 500;
            exp.Account__c = account.Id;

            newExps.add(exp);
        }
        Test.startTest();
        insert newExps;
        Test.stopTest();

        Account__c updatedAccount = [SELECT ID, Amount__c FROM Account__c LIMIT 1];

        Assert.areEqual(2500.50, updatedAccount.Amount__c);
    }

    @IsTest
    static void createRevenues(){
        Account__c account = [SELECT ID, Amount__c FROM Account__c LIMIT 1];

        List<Revenue__c> newRev = new List<Revenue__c>();
        for(Integer i = 0; i < 5; i++){
            Revenue__c rev = new Revenue__c();
            rev.Name = 'Test'+i;
            rev.Amount__c = 500;
            rev.Account__c = account.Id;

            newRev.add(rev);
        }
        Test.startTest();
        insert newRev;
        Test.stopTest();

        Account__c updatedAccount = [SELECT ID, Amount__c FROM Account__c LIMIT 1];

        Assert.areEqual(7500.50, updatedAccount.Amount__c);
    }
}